id: I3AD7D847
ocr_import_info:
  timestamp: '2023-06-29T01:31:34.975656+00:00'
  batch_id: batch-a58f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-29 01:35:22.573322+00:00
last_modified: 2023-06-29 01:35:22.573328+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15940
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15940
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རིགས་པའི་ཚོགས་དྲུག་དང་བྱང་ཆུབ་སེམས་འགྲེལ།
  languages:
  - bo
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.993304738044816
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG15954:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15954
      total_pages: 232
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15954.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.993304738044816
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
